### PR TITLE
Fix for 2019.4 LTS

### PR DESCRIPTION
**Pull request by keijiro**
When opening the project with Unity 2019.4 LTS, due to a change of Package Manager in 2019.4.3, the Timeline package causes a compilation error with the following message.

> Library\PackageCache\com.unity.timeline@1.3.0\Runtime\Playables\ParticleControlPlayable.cs(25,91): error CS0246: The type or namespace name 'ParticleSystem' could not be found (are you missing a using directive or an assembly reference?)

The project must have an explicit dependency on the build-in particle system package to avoid this error.

### CODE REVIEW

**Comment by peeweek** [comment]
Well noticed! 
In The problem seems in fact more related to timeline which is supposed to assume this module could be disabled. The timeline package received a fix for that issue in the version 1.4.1. We're currently working on the upgrade for 2019.4 and we have upgraded the timeline package to 1.4.1 so it doesn't happen.
